server:
  port: 8002
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  main:
    web-application-type: servlet

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recipe?serverTimezone=Asia/Seoul
    username: sang
    password: sang0412

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      
  jwt:
    secret:
      asdasdasdasdadwikjnislhsfikjsfilskg
      
logging:
  level:
    org:
      springframework:
        security: DEBUG